---
inputs:
- type: git
  branch: master
  service: ${GIT_REPO}
  path: config/integrations
triggers:
- type: manual
  name: Manual Trigger
  eventListener: manual-integrations-listener
properties:
- name: test-property
  value: ${TEXT_TEST}
  type: text
- name: definitions_repo
  value: ${INTEGRATION_TEST}
  type: integration
  path: parameters
- name: morerepos
  value: ${INTEGRATION_TEST}
  type: integration
  path: parameters.repo_url
